### PR TITLE
Scrum 91 style the blogs page

### PR DESCRIPTION
**Pull request by SheilaOnyango**
### In this PR

- **Data Fetching**: Implemented Axios to fetch blog articles.
- **Blog Item Display**:  I have sorted articles by date in descending order.
- **Technology Filtering**: Implemented a filtering feature that allows users to view blog items based on selected technologies.

### Testing

- git checkout SCRUM-91-style-the-blogs-page
- npm run dev
- Go to the blogs page and check whether everything is working well.

### CODE REVIEW

**Comment by Randolph-dev** [comment]
Hey Sheila. Please remember to request a reviewer every time you open a PR. Otherwise, nobody will get a notification to review it. Since you are pushing database updates, this is very important, otherwise we will find ourselves scratching new incoming changes due to database merging errors from old PRs.

**Comment by Randolph-dev** [comment]
Also, there are two databases open in the backend. Please delete the old database before pushing changes to dev.

**Review by Randolph-dev — DISMISSED** [review]
Pulling db 1.9.gz gives me a working and responsive Blogs page where each article is filtered with available tags. Double check the Axios response is positive again before merging.

Also, I have issues finding the content for Blogs inside our Drupal content list. Can you tell me where it's being stored? Since there are two databases in the backend, I tried opening both, but 1.9 doesn't show me the content data, and 1.8 seems bugged(?) and I can't open it. 

Please address this and keep me updated, as I can't modify the database until this PR is merged.

**Comment by Randolph-dev** [comment]
Can you double check whether you forgot to push your updated database?

**Comment by SheilaOnyango** [comment]
### In this PR I

- **Data Fetching**: Implemented Axios to fetch blog articles.
- **Blog Item Display**: I have sorted articles by date in descending order.
- **Technology Filtering**: Implemented a filtering feature that allows users to view blog items based on selected technologies.

### Testing

- git pull origin dev
- lando db-import 1.1.gz(db with blog content)
- check Drupal to see whether blog content is available
- git checkout SCRUM-91-style-the-blogs-page
- npm run dev
- Go to the blogs page and check whether everything is working well.

**Review by alextrandev — APPROVED** [review]
Look gtm. I added 1 commit for the missing key prop and some clean up

**Pull request merged**
